DROP DATABASE OESDBNEW;

CREATE DATABASE IF NOT EXISTS OESDBNEW;

USE OESDBNEW;

DROP TABLE IF EXISTS Subject;

CREATE TABLE Subject(
 	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
     NAME VARCHAR(50) NOT NULL,
     DESCRIPTION VARCHAR(255)
);

-- DELETE FROM Exam;
-- DELETE FROM Question;
-- DELETE FROM Subject;
-- DELETE FROM Teacher;
-- DELETE FROM Student;


INSERT INTO Subject(NAME, DESCRIPTION) VALUES ('Python', 'Python-Desc');
INSERT INTO Subject(NAME, DESCRIPTION) VALUES ('C++', 'C++-Desc');
INSERT INTO Subject(NAME, DESCRIPTION) VALUES ('Java', 'Java-Desc');


DROP TABLE IF EXISTS Question;

CREATE TABLE Question(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SUBJECT_ID INT,
    QUESTION VARCHAR(255) NOT NULL,
    CHOICE1 VARCHAR(255) NOT NULL,
    CHOICE2 VARCHAR(255) NOT NULL,
    CHOICE3 VARCHAR(255) NOT NULL,
    CHOICE4 VARCHAR(255) NOT NULL,
    CHOICE1CORRECT boolean NOT NULL,
    CHOICE2CORRECT boolean NOT NULL,
    CHOICE3CORRECT boolean NOT NULL,
    CHOICE4CORRECT boolean NOT NULL,
    MARK INT
);

TRUNCATE TABLE Question;
 -- 1
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Python is an',
'interpreted, high-level, general-purpose programming language',
'object-oriented programming language',
'procedural, functional, structured, and reflective programming language',
'All the above',
0, 
0, 
0, 
1, 
1 
FROM SUBJECT WHERE NAME='Python';


-- 2
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Python is designed by',
'Guido van Rossum',
'James Gosling',
'Dennis Ritchie',
'Google',
0, 
1, 
0, 
0, 
1 
FROM SUBJECT WHERE NAME='Python';

-- 3
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Python first appeared in',
'January 1982',
'February 1991',
'December 1987',
'July 2001',
0, 
1, 
0, 
0, 
1 
FROM SUBJECT WHERE NAME='Python';

-- 4
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Python filename extensions is/are',
'.py',
'.pyi',
'.pyc and .pyd',
'All the above',
0, 
0, 
0, 
1, 
1 
FROM SUBJECT WHERE NAME='Python';


-- 5
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Python influenced by',
'C and C++',
'Java and Perl',
'Lisp and Haskell',
'All the above',
0, 
0, 
0, 
1, 
1 
FROM SUBJECT WHERE NAME='Python';



-- 1
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'C++ is a __________ programming language.',
'general-purpose',
'procedural and functional',
'object-oriented, generic, and modular',
'All the above',
0, 
0, 
0, 
1, 
1 
FROM SUBJECT WHERE NAME='C++';


-- 2
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'C++ designed by',
'Bjarne Stroustrup',
'Dennis Ritchie',
'James Gosling',
'Albert Einstein',
1, 
0, 
0, 
0, 
1 
FROM SUBJECT WHERE NAME='C++';


-- 3
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'C++ was first appeared in',
'1985',
'1984',
'1995',
'1994',
1, 
0, 
0, 
0, 
1 
FROM SUBJECT WHERE NAME='C++';

-- 4
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'C++ influenced by',
'C',
'Ada and ALGOL',
'Modula-2 and Simula',
'All the above',
0, 
0, 
0, 
1, 
1 
FROM SUBJECT WHERE NAME='C++';

-- 5
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'C++ influenced',
'Java',
'Perl, PHP and Python',
'C# and D',
'All the above',
0, 
0, 
0, 
1, 
1 
FROM SUBJECT WHERE NAME='C++';


-- 1
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'What do you understand by HTML?',
'HTML describes the structure of a webpage',
'HTML is the standard markup language mainly used to create web pages',
'HTML consists of a set of elements that helps the browser how to view the content',
'All of the above',
0,
0,
0,
1,
1
FROM SUBJECT WHERE NAME='HTML';

-- 2
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Who is the father of HTML?',
'Rasmus Lerdorf',
'Tim Berners-Lee',
'Brendan Eich',
'Sergey Brin',
0,
1,
0,
0,
1
FROM SUBJECT WHERE NAME='HTML';

-- 3
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'HTML stands for ___',
'HyperText Markup Language',
'HyperText Machine Language',
'HyperText Marking Language',
'HighText Marking Language',
1,
0,
0,
0,
1
FROM SUBJECT WHERE NAME='HTML';

-- 4
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Which is used to read an HTML page and render it?',
'Web server',
'Web network',
'Web browser',
'Web matrix',
0,
0,
3,
0,
1
FROM SUBJECT WHERE NAME='HTML';

-- 5
INSERT INTO Question(SUBJECT_ID, QUESTION, CHOICE1, CHOICE2, CHOICE3, CHOICE4, CHOICE1CORRECT, CHOICE2CORRECT, CHOICE3CORRECT, CHOICE4CORRECT, MARK) 
SELECT ID, 
'Which tag is used for inserting the largest heading in HTML?',
'head',
'<h1>',
'<h6>',
'heading',
0,
1,
0,
0,
1
FROM SUBJECT WHERE NAME='HTML';

DROP TABLE IF EXISTS teacher;

CREATE TABLE teacher(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REGISTRATIONNO	VARCHAR(50),
    TITLE VARCHAR(10),
    FIRSTNAME VARCHAR(50),
    MIDDLENAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    CONTACTNO VARCHAR(50),
    EMAILID VARCHAR(50),
    GENDER VARCHAR(10),
    STREET1 VARCHAR(50),
    STREET2 VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    PINCODE VARCHAR(50),
    PASSWORD VARCHAR(50)
);

TRUNCATE TABLE teacher;

INSERT INTO teacher(TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, GENDER, CONTACTNO, EMAILID, REGISTRATIONNO, CITY, STATE, STREET1, STREET2, PINCODE)
SELECT 'Mr.', 'Farazul', '', 'Hasan', 'Male', '8770364706', 'hasanfaraz862@gmail.com', 'REG-T-001', 'Baikunthpur, Korea', 'Chhattisgarh', 'Baikunthpur-Street01', 'Baikunthpur-Street02', '123456';

INSERT INTO teacher(TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, GENDER, CONTACTNO, EMAILID, REGISTRATIONNO, CITY, STATE, STREET1, STREET2, PINCODE)
SELECT 'Mr.', 'Dhushasan', '', 'Mahanta', 'Male', '9437476359', 'dhushasan.2011@gmail.com', 'REG-T-002', 'Keonjhar', 'Odisha', 'Keonjhar-Street01', 'Keonjhar-Street02', '123456';

INSERT INTO teacher(TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, GENDER, CONTACTNO, EMAILID, REGISTRATIONNO, CITY, STATE, STREET1, STREET2, PINCODE)
SELECT 'Ms.', 'Madhavi', '', 'Goswami', 'Female', '8860876246', 'Madhavigoswami121@gmail.com', 'REG-T-006', 'Ghaziabad Uttar', 'Pradesh', 'Ghaziabad-Street01', 'Ghaziabad-Street02', '123456';

UPDATE TEACHER SET PASSWORD=REGISTRATIONNO;

DROP TABLE IF EXISTS student;

CREATE TABLE student(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REGISTRATIONNO	VARCHAR(50),
    TITLE VARCHAR(10),
    FIRSTNAME VARCHAR(50),
    MIDDLENAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    CONTACTNO VARCHAR(50),
    EMAILID VARCHAR(50),
    GENDER VARCHAR(10),
    STREET1 VARCHAR(50),
    STREET2 VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    PINCODE VARCHAR(50),
    PASSWORD VARCHAR(50)
);

TRUNCATE TABLE student;

INSERT INTO student(TITLE, REGISTRATIONNO, FIRSTNAME, MIDDLENAME, LASTNAME, CONTACTNO, GENDER) SELECT 'Ms.', 'REG-1001', 'RAKSHITA', 'SHYAM', 'SINGH', '8902467580', 'Female';
INSERT INTO student(TITLE, REGISTRATIONNO, FIRSTNAME, MIDDLENAME, LASTNAME, CONTACTNO, GENDER) SELECT 'Mr.', 'REG-1002', 'Irfan', 'Rahaman', 'Anisur', '8638045954', 'Male';
INSERT INTO student(TITLE, REGISTRATIONNO, FIRSTNAME, MIDDLENAME, LASTNAME, CONTACTNO, GENDER) SELECT 'Mr.', 'REG-1003', 'NITISH', 'SHARMA', 'NEELAM', '9780229407', 'Male';
INSERT INTO student(TITLE, REGISTRATIONNO, FIRSTNAME, MIDDLENAME, LASTNAME, CONTACTNO, GENDER) SELECT 'Ms.', 'REG-1004', 'beauty', 'singh', 'Rama', '7889224126', 'Female';

UPDATE STUDENT SET PASSWORD=REGISTRATIONNO;

DROP TABLE IF EXISTS Exam;

CREATE TABLE Exam(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SUBJECT_ID INT NOT NULL,	
    DESCRIPTION VARCHAR(255),
    NOOFQUESTIONS INT,
    EXAMDATE DATETIME
);

TRUNCATE TABLE Exam;

INSERT INTO Exam(SUBJECT_ID, NOOFQUESTIONS, DESCRIPTION)
SELECT ID, 10, 'Python-Beginner-Test' FROM Subject WHERE NAME='Python';

INSERT INTO Exam(SUBJECT_ID, NOOFQUESTIONS, DESCRIPTION)
SELECT ID, 10, 'C++-Beginner-Test' FROM Subject WHERE NAME='C++';